name: Merge Prod Changes into Non-Prod Branches

on:
    workflow_run:
      workflows:
        - Release-Prod
      types:
        - completed
    workflow_dispatch:

jobs:
  merge-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout production branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: production

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge production into dev
        run: |
          git checkout dev
          git merge production --no-edit
          git push origin dev

      - name: Merge production into new_qa
        run: |
          git checkout new_qa
          git merge production --no-edit
          git push origin new_qa

      - name: Merge production into new_uat
        run: |
          git checkout new_uat
          git merge production --no-edit
          git push origin new_uat